### ISSUE TITLE
plog2wp.py UnicodeEncodeError

### ISSUE THREAD

**Issue by acoul** [hago/hello-world#1]
greetings,

tried to use the plog2wp.py in an attempt to migrate an old lifetype/plog system to a latest wordpress and bumped to the following error:

> Traceback (most recent call last):
>   File "plog2wp.py", line 107, in <module>
>     run()
>   File "plog2wp.py", line 102, in run
>     id = wpsql("insert into > > wp_posts(post_author,post_date,post_date_gmt,post_content,post_title,post_status,post_name,post_excerpt,to_ping,pinged,post_content_filtered) values(%s,'%s','%s','%s','%s','%s','%s','','','','%s')" % (wuid,arc.date,arc.date,arc.text,arc.topic,arc.status,arc.topic,arc.textfiltered))
>   File "plog2wp.py", line 40, in wpsql
>     print sql
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 244: ordinal not in range(128)

**Comment by hago** [comment]
I used this script years ago and I don't have plog db to verify at present. But It's encoding error, I'm sure about that. Cause could be one of following: 

- In my case, I had created my plog db and wp db both in utf8, you may need to change those accordingly.
- or, current mysqldb's behavior changed, it stores query result in unicode(unicode type for 2, string type for 3) and expects raw byte series(string type for 2, bytes type for 3) for insert. If that's true, try adding _.encode('encoding')_ for those text fields while inserting.

**Comment by hago** [comment]
I used this script years ago and I don't have plog db to verify at present. But It's encoding error, I'm sure about that. Cause could be one of following: 

- In my case, I had created my plog db and wp db both in utf8, you may need to change those accordingly.
- or, current mysqldb's behavior changed, it stores query result in unicode(unicode type for 2, string type for 3) and expects raw byte series(string type for 2, bytes type for 3) for insert. If that's true, try adding _.encode('encoding')_ for those text fields while inserting.

> greetings,
> 
> tried to use the plog2wp.py in an attempt to migrate an old lifetype/plog system to a latest wordpress and bumped to the following error:
> 
> > Traceback (most recent call last):
> > File "plog2wp.py", line 107, in 
> > run()
> > File "plog2wp.py", line 102, in run
> > id = wpsql("insert into > > wp_posts(post_author,post_date,post_date_gmt,post_content,post_title,post_status,post_name,post_excerpt,to_ping,pinged,post_content_filtered) values(%s,'%s','%s','%s','%s','%s','%s','','','','%s')" % (wuid,arc.date,arc.date,arc.text,arc.topic,arc.status,arc.topic,arc.textfiltered))
> > File "plog2wp.py", line 40, in wpsql
> > print sql
> > UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 244: ordinal not in range(128)

**Comment by acoul** [comment]
thank you so much for your response. this is an old plog system that at some point I updated to latest lifetype. so it's probably a mixed latin1/utf8 environment that still somehow works. as sql & pyhon aren't my strongest points, if you are interested, I can email you the database dump since it's not that big, so you can have a look.

**Comment by hago** [comment]
I'm afraid I can't garantee you a time point. if that's ok for you, send me dump of both the plog and wp db.


Sent from Blackberry Hub

发件人： notifications@github.com
发送时间： 2019年11月8日 01:52
收件人： hello-world@noreply.github.com
回复： reply@reply.github.com
抄送： suncjs@hagoapp.com; comment@noreply.github.com
主题： Re: [hago/hello-world] plog2wp.py UnicodeEncodeError (#1)


thank you so much for your response. this is an old plog system that at some point I updated to latest lifetype. so it's probably a mixed latin1/utf8 environment that still somehow works. as sql & pyhon aren't my strongest points, if you are interested, I can email you the database dump since it's not that big, so you can have a look. you may find me here: alex AT ozo.com

―

**Comment by acoul** [comment]
I've just emailed you the pointers where you may download both dumps

many regards

**Comment by acoul** [comment]
for any future desperate lifetype users, a few pointers:

https://github.com/lo-windigo/lifetype-export
http://git.ozo.com/?p=lifetype/.git;a=summary

**Comment by hago** [comment]
Alex
I tried to reproduce this error but failed, but maybe it’s not a bad thing. As you can see, when I wrote this script, I was using python 2 with mysqldb 1.x. However, when I debug this using my present env: python3 with a mysqldbwrapper called mysql, it works without any errors. I didn’t change anything except make it compatible with python3 syntax.
I verified it under windows and linux both. I don’t know about your environment, but it worth a try.
Install a python 3.7/3.8, then pip install mysql. I sent you my modified code in attachment.
Btw, there’s an issue in the data you sent me: there’s no only one user ‘alex’ in target wp db and this user doesn’t have any posts in source plog db. I just update all posts to user alex before I manage to finish test.

Thanks

发件人: Alexandros C. Couloumbis <notifications@github.com>
发送时间: 2019年11月26日 23:38
收件人: hago/hello-world <hello-world@noreply.github.com>
抄送: Chaojun Sun <suncjs@hagoapp.com>; Comment <comment@noreply.github.com>
主题: Re: [hago/hello-world] plog2wp.py UnicodeEncodeError (#1)


for any future desperate lifetype users, a few pointers:

https://github.com/lo-windigo/lifetype-export<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flo-windigo%2Flifetype-export&data=02%7C01%7C%7C0fcab9780e4444e83b7008d772869ba8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637103794767038759&sdata=e1FDeNT3UnDxnRvzQijQwpD0ihneH7zbDBXq46b7m%2Fo%3D&reserved=0>
http://git.ozo.com/?p=lifetype/.git;a=summary<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgit.ozo.com%2F%3Fp%3Dlifetype%2F.git%3Ba%3Dsummary&data=02%7C01%7C%7C0fcab9780e4444e83b7008d772869ba8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637103794767048771&sdata=ujwtkx67o4R33MH4XEtFMfkcAIgcZuvPjA4iFrT%2FJ5c%3D&reserved=0>

**Comment by acoul** [comment]
how can I get a copy of your modified script in order to give it a try?
([Reference](https://github.com/hago/hello-world/issues/1))

**Comment by hago** [comment]
I did attach a copy in last mail, but it looks like this thread is to github comments instead your personal email.
I pushed the modified version to my repo, you could pull the updated version.

发件人: Alexandros C. Couloumbis <notifications@github.com>
发送时间: 2019年12月15日 00:09
收件人: hago/hello-world <hello-world@noreply.github.com>
抄送: Chaojun Sun <suncjs@hagoapp.com>; Comment <comment@noreply.github.com>
主题: Re: [hago/hello-world] plog2wp.py UnicodeEncodeError (#1)


how can I get a copy of your modified script in order to give it a try?
(Reference<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhago%2Fhello-world%2Fissues%2F1&data=02%7C01%7C%7C608745c50a944a08ed6f08d780aff351%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637119365493108704&sdata=zKdWziBn00eb5dJHzTYYHfUli15llmswtg0KkPHJWP8%3D&reserved=0>)
